apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template
  title: Create React App Template
  description: Create a new CRA website project
  tags:
    - react
    - cra
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      properties:
        name:
          title: Name
          type: string
          description: The name assigned to all of the frontend objects defined in this template.
          ui:field: EntityNamePicker
          default: react-web-app
        memorylimit:
          title: Memory Limit
          type: string
          description: Maximum amount of memory the container can use.
          default: 512Mi
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: github.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: ocp-rhdh-poc
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: "https://github.com/ocp-rhdh-poc/react-web-app"
        targetPath: ./workspace

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.name}}"
        repoVisibility: public
        sourcePath: ./workspace

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: "https://github.com/ocp-rhdh-poc/react-web-appmas-gitops/tree/master"
        values:
          name: ${{ parameters.name }}
          memorylimit: ${{ parameters.memorylimit }}
          source_repository: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.name}}.git
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:github
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.name}}-gitops"
        title: gitops resources for ${{ parameters.name }}
        description: gitops resources for ${{ parameters.name }}
        sourcePath: ./tenant-gitops
        repoVisibility: public

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
